### ISSUE TITLE
bug in the unity console

### ISSUE THREAD

**Issue by polyren** [github-beta/unity-preview#24]
Please fill out the data below and include a zip with the Unity log file and the extension log file.
On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnityDebug\github-unity.log`
On macOS, the extension log file is at `~/.local/share/GitHubUnityDebug/github-unity.log`

If you prefer not to submit your log files through the issue tracker, send them
to unity@github.com with the issue number.

Version of Unity (eg. 5.5.0f1):
Version of GitHub for Unity (see console output):
Platform (eg. Windows, macOS, Linux):

What happened

**Comment by polyren** [comment]
```
09:48:32 AM WARN [ 2] <GitInstaller>                      Archive "PlatformResources\windows\git-lfs.zip" missing
09:49:13 AM ERROR [ 3] <TaskRunner>                        
Task_Start_ContinuationTask
  at System.Threading.Tasks.Task.Start (System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at GitHub.Unity.BaseTask.Run (CancellationToken cancellationToken) [0x00030] in /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/Tasks/BaseTask.cs:87 
  at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3 () [0x0000e] in /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:218 
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex, System.String message) in /Users/shana/code/work/github/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 168
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex) in /Users/shana/code/work/github/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 174
   at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3() in /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:line 222
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TaskExecuteWaitCallback(System.Object obj)
09:53:43 AM WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
09:53:43 AM WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
09:53:44 AM INFO [ 1]                                     Initializing GitHub for Unity version 0.9.1.0
```


in the unity the console log gives me several error report,
```
Failed to load 'Assets/Editor/GitHub/sfw.dll' with error '找不到指定的模块。'.
GitHub.Unity.RepositoryWatcher:Initialize() (at /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/Events/RepositoryWatcher.cs:70)
GitHub.Unity.RepositoryWatcher:Initialize() (at /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/Events/RepositoryWatcher.cs:69)
GitHub.Unity.RepositoryManager:Initialize() (at /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/RepositoryManager.cs:178)
GitHub.Unity.<RestartRepository>c__async0:MoveNext() (at /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/ApplicationManagerBase.cs:97)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start(<RestartRepository>c__async0&)
GitHub.Unity.ApplicationManagerBase:RestartRepository()
GitHub.Unity.ApplicationManager:RestartRepository() (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationManager.cs:91)
GitHub.Unity.<RunInternal>c__async1:MoveNext() (at /Users/shana/code/work/github/UnityInternal/src/GitHub.Api/ApplicationManagerBase.cs:121)
System.Threading.Tasks.ThreadPoolTaskScheduler:TaskExecuteWaitCallback(Object)
```

and

```
NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.ProjectWindowInterface.OnProjectWindowItemGUI (System.String guid, Rect itemRect) (at /Users/shana/code/work/github/UnityInternal/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs:233)
UnityEditor.ObjectListArea+LocalGroup.DrawItem (Rect position, UnityEditor.FilterResult filterItem, UnityEditor.BuiltinResource builtinResource, Boolean isFolderBrowsing) (at C:/buildslave/unity/build/Editor/Mono/ObjectListLocalGroup.cs:855)
UnityEditor.ObjectListArea+LocalGroup.DrawInternal (Int32 beginIndex, Int32 endIndex, Single yOffset) (at C:/buildslave/unity/build/Editor/Mono/ObjectListLocalGroup.cs:192)
UnityEditor.ObjectListArea+Group.Draw (Single yOffset, Vector2 scrollPos) (at C:/buildslave/unity/build/Editor/Mono/ObjectListGroup.cs:144)
UnityEditor.ObjectListArea.HandleListArea () (at C:/buildslave/unity/build/Editor/Mono/ObjectListArea.cs:1367)
UnityEditor.ObjectListArea.OnGUI (Rect position, Int32 keyboardControlID) (at C:/buildslave/unity/build/Editor/Mono/ObjectListArea.cs:562)
UnityEditor.ProjectBrowser.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/ProjectBrowser.cs:1754)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)


```

**Comment by StanleyGoldman** [comment]
Hey @polyren thanks for testing and the bug report.

Can you tell me what platform you are running on?

**Comment by StanleyGoldman** [comment]
These three issues are being tracked separately: #8, #30, #31
So I'm going to close this up.

**Comment by polyren** [comment]
yes, I'm using pc.


2017-04-24 7:48 GMT-04:00 Stanley Goldman <notifications@github.com>:
