### ISSUE TITLE
Imposible to login with my GitHub Credentials

### ISSUE THREAD

**Issue by PPeMg** [github-beta/unity-preview#38]
Version of Unity: 5.4.1f1
Version of GitHub for Unity: 0.10.0.0
Platform: Windows 10

When I introduce my account data on the login prompt,  it doesn't work and just show a message "Login failed". I revised my login data and it works at my browser.

[github-unity.log.txt](https://github.com/github-beta/unity-preview/files/981206/github-unity.log.txt)
[Editor.log.txt](https://github.com/github-beta/unity-preview/files/981207/Editor.log.txt)

**Comment by StanleyGoldman** [comment]
Hey @PPeMg thanks for testing and thanks for the feedback. I've been working on authentication bugs last week. Hopefully I can say we've solved your problem for our next release.

```
00:00:36 AM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
00:00:36 AM INFO [ 1] <LoginManager>                      Login Username:PPeMg
00:00:38 AM WARN [ 1] <LoginManager>                      Login Exception
An error occurred while sending the request
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x003fe] in D:\code\github\UnityInternal\submodules\dotnet-httpClient35\System.Net.Http\System.Net.Http\HttpClientHandler.cs:363 
   at GitHub.Unity.LogAdapterBase.Warning(System.Exception ex, System.String message) in D:\code\github\UnityInternal\src\GitHub.Logging\LogAdapterBase.cs:line 140
   at GitHub.Unity.LoginManager+<Login>c__async0.MoveNext() in D:\code\github\UnityInternal\src\GitHub.Api\Authentication\LoginManager.cs:line 126
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c__DisplayClassa.<OnCompletedInternal>b__1(System.Object state)
   at GitHub.Unity.MainThreadSynchronizationContext+<Post>c__AnonStorey1.<>m__0() in D:\code\github\UnityInternal\src\UnityExtension\Assets\Editor\GitHub.Unity\Threading\SingleThreadSynchronizationContext.cs:line 25
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:line 232
```

**Comment by StanleyGoldman** [comment]
Hey @PPeMg I have not been able to reproduce your issue, but there are some fixes to the login process in the latest release.

Could you try to reproduce the error and capture another log?

**Comment by StanleyGoldman** [comment]
Hey @PPeMg! There is a new repo and a new build out. https://github.com/github-for-unity/Unity/releases
Give it a shot and I think it should resolve your issues.

**Comment by PPeMg** [comment]
I'm gonna test it and I post my results. Thank you very much
