### ISSUE TITLE
Never ends the push action - Ubuntu 16.10

### ISSUE THREAD

**Issue by ma1onso** [github-beta/unity-preview#5]
**NOT github-unity.log file created** but this message is show: Initializing GitHub for Unity log file: /home/amarok/.local/share/GitHubUnityDebug/github-unity.log

**Version of Unity**: 5.6.0xf3Linux
**Version of GitHub for Unity**: 0.8.0.0
**Platform**: Linux (Ubuntu 16.10)

Never ends the **push** action

[UnityEditor.log.zip](https://github.com/github-beta/unity-preview/files/911684/UnityEditor.log.zip)

**Comment by StanleyGoldman** [comment]
Hey @alons45 thanks for testing and for the bug report.

**Comment by infinstarlight** [comment]
The same thing happens on macOS, same version of Unity and GitHub.

EDIT: It also causes Unity/MonoDevelop to crash

**Comment by StanleyGoldman** [comment]
Thanks for trying @professionaljones 
I'll update this thread when we think we have that bug sniffed out.

**Comment by coty-crg** [comment]
+1 for windows 10 as well

**Comment by shana** [comment]
Is this happening consistently for you, or does it ever successfully push?

@coty-crg Given that you're on Windows, can you try opening the command line via the `GitHub` menu in Unity and running `git push` from there, to see if that works or equally hangs?

**Comment by ma1onso** [comment]
@shana I don't understand

**Comment by shana** [comment]
@alons45 How many times have you tried to push with GitHub for Unity, and does it hang every time?

**Comment by StanleyGoldman** [comment]
Also, @alons45 is running on Linux and did not get a `github-unity.log`
In Issue #7, @sevelee experienced similar behavior on mac and was able to retrieve a log.

```
13:08:27 PM ERROR [ 3] <TaskRunner>                        
Task_Start_ContinuationTask
  at System.Threading.Tasks.Task.Start (System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at GitHub.Unity.BaseTask.Run (CancellationToken cancellationToken) [0x00030] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/BaseTask.cs:87 
  at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3 () [0x0000e] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:218 
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex, System.String message) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 148
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 154
   at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3() in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:line 222
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TaskExecuteWaitCallback(System.Object obj)
13:08:27 PM ERROR [ 3] <TaskRunner>                        
SwitchToThread
  at (wrapper managed-to-native) System.Threading.Platform:SwitchToThread ()
  at System.Threading.Platform.Yield () [0x00000] in <filename unknown>:0 
  at System.Threading.ManualResetEventSlim.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InternalWait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.SimpleTask.Run (CancellationToken cancellationToken) [0x00042] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/BaseTask.cs:42 
  at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3 () [0x0000e] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:218 
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex, System.String message) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 148
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 154
   at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3() in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:line 222
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TaskExecuteWaitCallback(System.Object obj)
13:08:27 PM DEBUG [ 4] <RepositoryWatcher>                 Native interface is disabled
13:12:23 PM WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
13:12:23 PM WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
13:12:33 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.8.0.0
13:12:33 PM WARN [ 2] <GitInstaller>                      Archive "PlatformResources/mac/git.zip" missing
13:12:33 PM WARN [ 2] <GitInstaller>                      Archive "Assets/Editor/GitHub/PlatformResources/mac/git.zip" missing, returning
13:12:34 PM DEBUG [ 2] <RepositoryWatcher>                 Native interface is disabled
13:13:14 PM ERROR [ 3] <TaskRunner>                        
SwitchToThread
  at (wrapper managed-to-native) System.Threading.Platform:SwitchToThread ()
  at System.Threading.Platform.Yield () [0x00000] in <filename unknown>:0 
  at System.Threading.ManualResetEventSlim.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InternalWait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.SimpleTask.Run (CancellationToken cancellationToken) [0x00042] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/BaseTask.cs:42 
  at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3 () [0x0000e] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:218 
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex, System.String message) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 148
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 154
   at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3() in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:line 222
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TaskExecuteWaitCallback(System.Object obj)
13:13:20 PM ERROR [ 2] <GitCredentialManager>              Failed to get the credential helper
13:14:54 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.8.0.0
13:14:54 PM WARN [ 2] <GitInstaller>                      Archive "PlatformResources/mac/git.zip" missing
13:14:54 PM WARN [ 2] <GitInstaller>                      Archive "Assets/Editor/GitHub/PlatformResources/mac/git.zip" missing, returning
13:14:54 PM DEBUG [ 2] <RepositoryWatcher>                 Native interface is disabled
13:17:33 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
13:17:33 PM INFO [ 1] <LoginManager>                      Login Username:sevelee
13:17:36 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
13:18:26 PM ERROR [ 3] <TaskRunner>                        
SwitchToThread
  at (wrapper managed-to-native) System.Threading.Platform:SwitchToThread ()
  at System.Threading.Platform.Yield () [0x00000] in <filename unknown>:0 
  at System.Threading.ManualResetEventSlim.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.InternalWait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.SimpleTask.Run (CancellationToken cancellationToken) [0x00042] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/BaseTask.cs:42 
  at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3 () [0x0000e] in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:218 
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex, System.String message) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 148
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex) in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Logging/LogAdapterBase.cs:line 154
   at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3() in /Users/stanleygoldman/Documents/UnityInternal/src/GitHub.Api/Tasks/TaskRunnerBase.cs:line 222
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TaskExecuteWaitCallback(System.Object obj)
13:19:09 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.8.0.0
13:19:09 PM WARN [ 4] <GitInstaller>                      Archive "PlatformResources/mac/git.zip" missing
13:19:09 PM WARN [ 4] <GitInstaller>                      Archive "Assets/Editor/GitHub/PlatformResources/mac/git.zip" missing, returning
13:19:09 PM DEBUG [ 4] <RepositoryWatcher>                 Native interface is disabled
13:19:19 PM ERROR [ 5] <GitCredentialManager>              Failed to get the credential helper
```

**Comment by ma1onso** [comment]
@shana consistently (in every push)

**Comment by supremacey** [comment]
I have problem with pull/push action with 2F Auth.
When I try to pull/push changes in Unity Editor it either:
- flashes the git push/pull progress bar
- hangs on progress bar (have to Force Quit Unity) - this behaviour is most frequent

In both ways it doesn’t push an changes to remote repo.
At the same time I am still able to pull/push changes with command line git using auth token.

Logs don’t seem to tell much more:
```
08:26:42 AM INFO [ 1]                                     Initializing GitHub for Unity version 0.9.1.0
08:26:42 AM WARN [ 2] <GitInstaller>                      Archive "PlatformResources/mac/git.zip" missing
08:26:42 AM WARN [ 2] <GitInstaller>                      Archive "Assets/Editor/GitHub/PlatformResources/mac/git.zip" missing, returning
08:26:42 AM WARN [ 2] <GitInstaller>                      Archive "PlatformResources/mac/git-lfs.zip" missing
08:26:43 AM DEBUG [ 2] <RepositoryWatcher>                 Native interface is disabled
——— and push action goes here ——
08:33:41 AM ERROR [ 2] <GitCredentialManager>              Failed to get the credential helper
```

__edit__: forgot to mention that I am on macOS

**Comment by bhison** [comment]
Also experiencing this issue with Unity 5.4.2f on MacOS Sierra

I also don't seem to be able to access the in-unity command line. I suppose this may be a separate issue.

**Comment by shana** [comment]
@bhison Yup, the command line menu is broken, we're working on a fix for that!

**Comment by jessemcculloch** [comment]
This also fails for me every time.  Windows 10, Unity 5.6.0f3.  I can push my committed changes with GitHub desktop, just not from within Unity.

**Comment by StanleyGoldman** [comment]
Hey all, we just released our latest build. There were a lot of fixes to the authentication process. Give it a shot and let me know how it goes.

**Comment by StanleyGoldman** [comment]
Hey everyone! There is a new repo and a new build out. Can I ask everyone to give it a shot?
https://github.com/github-for-unity/Unity
